#!/bin/sh
# ===== PBS OPTIONS =====
#PBS -q PCA
### Specify the size of your job array: This should match the number of paths in the paths array below.
#PBS -t 1-7
#PBS -N JED
#PBS -l nodes=1:ppn=2
#PBS -l mem=6gb
#PBS -l walltime=1:59:59
#PBS -o /dev/null
#PBS -e /dev/null
# ===== END PBS OPTIONS =====
SHORT_JOBID=`echo $PBS_JOBID |cut -d. -f1`
JOBNAME=`echo $PBS_JOBNAME |cut -d- -f1`
exec 1>&2>$PBS_O_WORKDIR/JED-SUMMARY-$SHORT_JOBID

dir=`pwd`
echo "The Bash Working Directory:  "$dir
echo "The PBS _O_WORKDIR:  "$PBS_O_WORKDIR

### YOU MUST SPECIFY THE PATHS TO THE JED INPUT FILES IN THE PATHS ARRAY:

paths=(
"/nfs/cbr-fs2/vol1/projects/dcm/JED/1ake/300/pdb/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/JED/1ake/322/pdb/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/JED/1ake/400/pdb/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/Trajectories_For_Charles/JED_Chris/A_ALL/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/Trajectories_For_Charles/JED_Chris/B_ALL/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/Trajectories_For_Charles/JED_Chris/D_ALL/JED_Driver.txt" 
"/nfs/cbr-fs2/vol1/projects/dcm/Trajectories_For_Charles/JED_Chris/JED_Driver.txt")

index=${PBS_ARRAYID}

path=${paths[$index-1]}
echo "The Input File Path:  "$path

cd $PBS_O_WORKDIR

java -jar -d64 -Xms4096m -Xmx6144m -XX:MaxPermSize=1024m JED_Driver.jar $path
